org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

minecraft_version=26.3
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

mod_version=1.2.0+26.3
maven_group=avox.weather_notifier
archives_base_name=weather_notifier

fabric_version=0.162.0+26.3
yacl_version=3.9.7+26.3-fabric
modmenu_version=21.0.0
